bool CheckCurve();
void AddPointToCurve(int x,int y,bool Final,unsigned char Type);
void DrawCurves();
void AddPointToCurve(int x,int y,bool Final,unsigned char Type);
bool CheckPointInside(int x,int y);
int GetCurveDistance1(int x,int y);
int GetCrossProportion(int x0,int y0,int x1,int y1);
void SetTextureInCurve();
void SetPlatoInCurve();
void SoftRegion();
void ClearCurve();
extern int PlatoHi;
extern int SurfType;
class PaintHills{
public:
	unsigned short NLayers;
	unsigned short TexAmount[32];
	unsigned short Texs[32][8];
	unsigned short TexStartHi[32];
	unsigned short TexEndHi[32];
	unsigned short TexStartAng[32];
	unsigned short TexEndAng[32];
	unsigned char CondType[32];
	unsigned char Param1[32];
	unsigned char Param2[32];
	int NHiSections;
	int HiSect[8];
};
void PaintAllMap(unsigned char* VertHi,unsigned char* VertType,PaintHills* PHL,int NTypes);
void SetPlatoInCurve(unsigned char* VertHi,unsigned char* VertType,unsigned char Type);
void SoftRegion(unsigned char* MpVertHi);